import { useEffect, useState, useRef, useCallback } from "react";
import { io } from "socket.io-client";
import "./AdminDashboard.css";
import { useNavigate } from "react-router-dom";


export default function AdminDashboard() {
  const [activeTab, setActiveTab] = useState("patients");
  const [patients, setPatients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false); // Mobile sidebar state

  // ── Messages / Chat State ──────────────────────────────────────────
  const [conversations, setConversations] = useState([]);
  const [selectedConv, setSelectedConv] = useState(null);
  const [convMessages, setConvMessages] = useState([]);
  const [adminInput, setAdminInput] = useState("");
  const [convLoading, setConvLoading] = useState(false);
  const [patientTyping, setPatientTyping] = useState(false);
  const adminSocketRef = useRef(null);
  const adminMsgEndRef = useRef(null);

  // ── Assign Dietician State ─────────────────────────────────────────
  const [showAssignModal, setShowAssignModal] = useState(false);
  const [assignTarget, setAssignTarget] = useState(null);
  const [assignName, setAssignName] = useState("");
  const [assignLoading, setAssignLoading] = useState(false);


  const [selectedPatient, setSelectedPatient] = useState(null);
  const [formData, setFormData] = useState({});
  const [showEditModal, setShowEditModal] = useState(false);

  // 🔹 Prescription states
  const [showPrescriptionModal, setShowPrescriptionModal] = useState(false);
  const [prescriptions, setPrescriptions] = useState([]);
  const [loadingPrescriptions, setLoadingPrescriptions] = useState(false);
  const [viewingPrescription, setViewingPrescription] = useState(null);

  const navigate = useNavigate();
  const [showDietModal, setShowDietModal] = useState(false);
  const [dietPlan, setDietPlan] = useState(null);
  const [editMode, setEditMode] = useState(false);
  const [editablePlan, setEditablePlan] = useState(null);
  const [selectedUser, setSelectedUser] = useState(null);
  const [trackingMeals, setTrackingMeals] = useState([]);

  const [popup, setPopup] = useState({
    show: false,
    message: "",
    type: "success", // success | error
  });





  const handleOpenDiet = async (user) => {
    try {
      setSelectedUser(user);
      setSelectedPatient(user); // Fix modal title which uses selectedPatient?.name

      const res = await fetch(
        `/api/diet/user/${user.id}`
      );

      if (!res.ok) throw new Error("Failed to fetch diet");

      const diets = await res.json();

      // take latest diet (last generated)
      const latestDiet = diets[diets.length - 1];

      const parsedPlan = JSON.parse(latestDiet.ai_generated_plan);

      try {
        const trackRes = await fetch(`/api/meal-tracking/user/${user.id}`);
        if (trackRes.ok) {
          const trackData = await trackRes.json();
          console.log("Admin Fetched Tracking Data:", trackData);
          setTrackingMeals(trackData.meals || []);
        } else {
          setTrackingMeals([]);
        }
      } catch (e) {
        console.error("Tracking fetch error", e);
        setTrackingMeals([]);
      }

      setDietPlan(latestDiet);
      setEditablePlan(parsedPlan);
      setEditMode(false);
      setShowDietModal(true);

    } catch (err) {
      console.error("Open diet error:", err);
      setPopup({
        show: true,
        message: "No diet Plan is Generated By the Patient",
        type: "error",
      });
    }
  };





  const handleDietDraftSave = () => {
    setEditMode(false);
  };








  const handleApproveDiet = async () => {
    try {
      const dieticianName = window.prompt("Enter Your Name (Approved by):", "Dietitian");
      if (dieticianName === null) return; // cancel

      const res = await fetch(
        `/api/diet/approve/${dietPlan.id}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            plan: editablePlan,
            approved_by: dieticianName,
          }),
        }
      );


      if (!res.ok) throw new Error("Approval failed");

      const data = await res.json();

      setDietPlan(prev => ({
        ...prev,
        status: "approved",
        ai_generated_plan: JSON.stringify(editablePlan),
        approved_at: data.approved_at,
        approved_by: dieticianName,
      }));

      // ✅ Manual state update for immediate table refresh
      setPatients(prev => prev.map(p => p.id === selectedUser.id ? { ...p, assigned_dietician: dieticianName } : p));

      setPopup({
        show: true,
        message: "Diet Approved ✅",
        type: "success",
      });

      setEditMode(false);
      fetchPatients();

    } catch (err) {
      console.error(err);
    }
  };

  const handleRejectDiet = async () => {
    try {
      const dieticianName = window.prompt("Enter Your Name (Rejected by):", "Dietitian");
      if (dieticianName === null) return; // cancel

      const res = await fetch(
        `/api/diet/reject/${dietPlan.id}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            approved_by: dieticianName,
          }),
        }
      );


      if (!res.ok) throw new Error("Rejection failed");

      const data = await res.json();

      setDietPlan(prev => ({
        ...prev,
        status: "rejected",
        approved_at: data.rejected_at,
        approved_by: dieticianName,
      }));

      // ✅ Manual state update for immediate table refresh
      setPatients(prev => prev.map(p => p.id === selectedUser.id ? { ...p, assigned_dietician: dieticianName } : p));

      setPopup({
        show: true,
        message: "Diet Rejected ❌",
        type: "error",
      });
      fetchPatients();

    } catch (err) {
      console.error(err);
    }
  };







  // Fetch patients + medical data
  const fetchPatients = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/users-medical", {
        headers: { Authorization: "Bearer " + localStorage.getItem("adminToken") },
      });
      if (!res.ok) throw new Error("Failed to fetch users");
      const data = await res.json();
      const mappedPatients = data.map((p) => ({
        id: p.userId,
        customerId: p.customer_id,
        medicalId: p.medicalId,
        name: p.full_name,
        gender: p.gender,
        condition: p.disease || p.condition_type || "N/A",
        creatinine: p.creatinine, potassium: p.potassium, sodium: p.sodium,
        urea: p.urea, estimatedGFR: p.estimated_gfr, albumin: p.albumin,
        calcium: p.calcium, phosphate: p.phosphate, uricAcid: p.uric_acid,
        cholesterolTotal: p.cholesterol_total, cholesterolLDL: p.cholesterol_ldl,
        cholesterolHDL: p.cholesterol_hdl, triglycerides: p.triglycerides,
        bloodPressureSystolic: p.blood_pressure_systolic, bloodPressureDiastolic: p.blood_pressure_diastolic,
        heartRate: p.heart_rate, bmi: p.bmi, fastingGlucose: p.fasting_glucose,
        hba1c: p.hba1c,
        assignedDietician: p.assigned_dietician,
        dietStatus: p.dietStatus,
      }));
      setPatients(mappedPatients);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchPatients();
  }, [fetchPatients]);

  // ── Socket.io for admin ─────────────────────────────────────────────
  useEffect(() => {
    const socket = io("http://localhost:8000", {
      transports: ["websocket", "polling"],
      auth: { token: localStorage.getItem("adminToken") },
    });
    adminSocketRef.current = socket;
    socket.on("connect", () => {
      socket.emit("join_room", { userId: "admin", role: "admin" });
    });
    socket.on("new_patient_message", (msg) => {
      setConvMessages((prev) => {
        if (selectedConv && msg.user_id === selectedConv.user_id) {
          return [...prev, { ...msg, timestamp: msg.created_at }];
        }
        return prev;
      });
      setConversations((prev) =>
        prev.map((c) =>
          c.user_id === msg.user_id
            ? { ...c, last_message: msg.message, last_sender: "patient", unread_count: c.unread_count + 1 }
            : c
        )
      );
    });
    socket.on("patient_typing", ({ userId, typing }) => {
      if (selectedConv && userId === selectedConv.user_id) setPatientTyping(typing);
    });
    return () => socket.disconnect();
  }, []);

  // scroll admin chat to bottom
  useEffect(() => {
    adminMsgEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [convMessages, patientTyping]);

  // ── Load conversations list ──────────────────────────────────────────
  useEffect(() => {
    if (activeTab !== "messages") return;
    fetch("/api/diet-chat/admin/all-conversations", {
      headers: { Authorization: "Bearer " + localStorage.getItem("adminToken") },
    })
      .then((r) => r.ok ? r.json() : [])
      .then(setConversations)
      .catch(() => {});
  }, [activeTab]);

  // ── Open a conversation ──────────────────────────────────────────────
  async function openConversation(conv) {
    setSelectedConv(conv);
    setConvLoading(true);
    setConvMessages([]);
    try {
      const res = await fetch(`/api/diet-chat/admin/history/${conv.user_id}`, {
        headers: { Authorization: "Bearer " + localStorage.getItem("adminToken") },
      });
      const data = await res.json();
      setConvMessages(data.map((m) => ({ ...m, timestamp: m.created_at })));
      // Mark as read
      fetch(`/api/diet-chat/mark-read/${conv.user_id}`, {
        method: "PATCH",
        headers: { Authorization: "Bearer " + localStorage.getItem("adminToken") },
      }).catch(() => {});
      setConversations((prev) =>
        prev.map((c) => c.user_id === conv.user_id ? { ...c, unread_count: 0 } : c)
      );
    } catch {} finally { setConvLoading(false); }
  }

  // ── Admin sends reply ────────────────────────────────────────────────
  function sendAdminReply() {
    const text = adminInput.trim();
    if (!text || !selectedConv) return;
    setAdminInput("");
    const optimistic = {
      id: `opt_${Date.now()}`,
      sender: "dietician",
      message: text,
      dietician: "Admin",
      timestamp: new Date().toISOString(),
    };
    setConvMessages((prev) => [...prev, optimistic]);
    if (adminSocketRef.current?.connected) {
      adminSocketRef.current.emit("dietician_message", {
        userId: selectedConv.user_id,
        message: text,
        dietician: "Admin",
      });
    } else {
      fetch("/api/diet-chat/send", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: "Bearer " + localStorage.getItem("adminToken") },
        body: JSON.stringify({ userId: selectedConv.user_id, message: text, sender: "dietician", dietician: "Admin" }),
      }).catch(() => {});
    }
  }

  // ── Assign Dietician ─────────────────────────────────────────────────
  async function handleAssignDietician() {
    if (!assignTarget || !assignName.trim()) return;
    setAssignLoading(true);
    try {
      const res = await fetch("/api/diet-chat/assign", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: "Bearer " + localStorage.getItem("adminToken") },
        body: JSON.stringify({ userId: assignTarget.id, dietician_name: assignName.trim() }),
      });
      if (!res.ok) throw new Error("Failed");
      setPatients((prev) =>
        prev.map((p) => p.id === assignTarget.id ? { ...p, assignedDietician: assignName.trim() } : p)
      );
      setPopup({ show: true, message: `Dietician "${assignName}" assigned to ${assignTarget.name} ✅`, type: "success" });
      setShowAssignModal(false);
      setAssignName("");
      setAssignTarget(null);
    } catch {
      setPopup({ show: true, message: "Failed to assign dietician ❌", type: "error" });
    } finally { setAssignLoading(false); }
  }






  const handleEdit = (patient) => {
    // console.log("Edit patient:", patient);

    // later:
    setSelectedPatient(patient)
    setFormData({ ...patient });
    setShowEditModal(true)

  };

  const handleCancel = () => {
    setEditingRowId(null);
    setFormData({});
  };





  const handleSaveMedical = async () => {
    try {
      const token = localStorage.getItem("adminToken");

      await fetch(
        `/api/admin/medical/${selectedPatient.medicalId}`,
        {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            creatinine: formData.creatinine,
            potassium: formData.potassium,
            sodium: formData.sodium,
            urea: formData.urea,
            estimated_gfr: formData.estimatedGFR,
            albumin: formData.albumin,
            calcium: formData.calcium,
            phosphate: formData.phosphate,
            uric_acid: formData.uricAcid,
            cholesterol_total: formData.cholesterolTotal,
            cholesterol_ldl: formData.cholesterolLDL,
            cholesterol_hdl: formData.cholesterolHDL,
            triglycerides: formData.triglycerides,
            blood_pressure_systolic: formData.bloodPressureSystolic,
            blood_pressure_diastolic: formData.bloodPressureDiastolic,
            heart_rate: formData.heartRate,
            bmi: formData.bmi,
            fasting_glucose: formData.fastingGlucose,
            postprandial_glucose: formData.postprandialGlucose,
            hba1c: formData.hba1c,
          }),
        }
      );

      // UI update
      setPatients((prev) =>
        prev.map((p) =>
          p.id === selectedPatient.id ? { ...p, ...formData } : p
        )
      );

      setShowEditModal(false);
      setSelectedPatient(null);

      // ✅ SHOW SUCCESS POPUP
      setPopup({
        show: true,
        message: "Medical data updated successfully ✅",
        type: "success",
      });


    } catch (err) {
      console.error(err);
      // alert("Medical update failed");
      setPopup({
        show: true,
        message: "Failed to update medical data ❌",
        type: "error",
      });
    }
  };









  const handleDelete = async (userId) => {
    if (!window.confirm("Are you sure you want to delete this patient?")) return;

    try {
      const token = localStorage.getItem("adminToken");

      const res = await fetch(
        `/api/admin/users/${userId}`,
        {
          method: "DELETE",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const data = await res.json();

      if (!res.ok) {
        alert(data.message || "Failed to delete patient");
        return;
      }

      // alert("Patient deleted successfully");

      // ✅ SHOW SUCCESS POPUP
      setPopup({
        show: true,
        message: "Medical data Deleted successfully ✅",
        type: "success",
      });


    } catch (err) {
      console.error("Delete error:", err);
      // alert("Server error while deleting");
      setPopup({
        show: true,
        message: "Failed to Delete the User Record ❌",
        type: "error",
      });
    }

  };




  const handleLogout = async () => {
    try {
      await fetch("/api/admin/logout", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("adminToken")}`,
        },
      });
    } catch (err) {
      console.error("Logout error", err);
    } finally {
      localStorage.removeItem("adminToken");

      // Clear browser cache
      if ('caches' in window) {
        caches.keys().then((names) => {
          names.forEach((name) => {
            caches.delete(name);
          });
        });
      }

      // Clear all storage
      sessionStorage.clear();
      localStorage.clear();

      navigate("/admin/login");
    }
  };


  const openPrescriptionViewer = (file) => {
    setViewingPrescription({
      name: file.file_name,
      type: file.file_type || "image/jpeg",
      url: `/api${file.file_path}`,
    });
  };


  /* ================= VIEW PRESCRIPTIONS ================= */
  const handleViewPrescriptions = async (patient) => {
    setSelectedPatient(patient);
    setShowPrescriptionModal(true);
    setLoadingPrescriptions(true);

    try {
      const res = await fetch(
        `/api/admin/users/${patient.id}/prescriptions`,
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("adminToken")}`,
          },
        }
      );

      const data = await res.json();
      setPrescriptions(data);
    } catch (err) {
      console.error("Prescription fetch error", err);

    } finally {
      setLoadingPrescriptions(false);
    }
  };


  // Group conversations by dietician for the sidebar
  const groupedConversations = conversations.reduce((acc, c) => {
    const dName = c.assigned_dietician || "Unassigned";
    if (!acc[dName]) acc[dName] = [];
    acc[dName].push(c);
    return acc;
  }, {});

  return (
    <div className="admin-layout">
      {/* Sidebar */}
      <aside className={`sidebar1 ${isSidebarOpen ? "open" : ""}`}>
        <div className="sidebar-header">
          <div className="header-content">
            <div className="avatar">AD</div>
            <h2>Patient Admin</h2>
            <button className="close-sidebar-btn" onClick={() => setIsSidebarOpen(false)}>×</button>
          </div>
        </div>

        <nav className="sidebar-nav">
          <ul>
            <li>
              <button
                className={`nav-item ${activeTab === "patients" ? "active" : ""}`}
                onClick={() => { setActiveTab("patients"); setIsSidebarOpen(false); }}
              >
                <span className="nav-icon">👥</span>
                <span className="nav-text">Patients</span>
              </button>
            </li>
            <li>
              <button
                className={`nav-item ${activeTab === "diet" ? "active" : ""}`}
                onClick={() => { setActiveTab("diet"); setIsSidebarOpen(false); }}
              >
                <span className="nav-icon">🍎</span>
                <span className="nav-text">Patient Diet</span>
              </button>
            </li>
            <li>
              <button
                className={`nav-item ${activeTab === "messages" ? "active" : ""}`}
                onClick={() => { setActiveTab("messages"); setIsSidebarOpen(false); }}
              >
                <span className="nav-icon">💬</span>
                <span className="nav-text">Messages</span>
              </button>
            </li>
            {/* <li>
              <button className={`nav-item ${activeTab === "reports" ? "active" : ""}`} onClick={() => setActiveTab("reports")}>
                <span className="nav-icon">📊</span>
                <span className="nav-text">Reports</span>
              </button>
            </li>
            <li>
              <button className={`nav-item ${activeTab === "settings" ? "active" : ""}`} onClick={() => setActiveTab("settings")}>
                <span className="nav-icon">⚙️</span>
                <span className="nav-text">Settings</span>
              </button>
            </li> */}
          </ul>
        </nav>

        <div className="sidebar-footer">
          <button className="logout-btn" onClick={handleLogout}>
            Logout  ➜]
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="main-content-1">
        <header className="header">
          <button className="hamburger-btn" onClick={() => setIsSidebarOpen(true)}>
            ☰
          </button>
          <h1>Admin Dashboard</h1>
          <div className="user-info">Welcome, Admin</div>
        </header>

        <div className="content-wrapper">
          {/* Patients */}
          {activeTab === "patients" && (
            <div className="dashboard-container active">
              {loading ? (
                <p>Loading patients...</p>
              ) : (
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Name</th>
                      <th>Assigned Dietician</th>
                      <th>Gender</th>
                      <th>Condition</th>
                      <th>Creatinine</th>
                      <th>Potassium</th>
                      <th>Sodium</th>
                      <th>Urea</th>
                      <th>Estimated GFR</th>
                      <th>Albumin</th>
                      <th>Calcium</th>
                      <th>Phosphate</th>
                      <th>Uric Acid</th>
                      <th>Cholesterol Total</th>
                      <th>Cholesterol LDL</th>
                      <th>Cholesterol HDL</th>
                      <th>Triglycerides</th>
                      <th>BP Systolic</th>
                      <th>BP Diastolic</th>
                      <th>Heart Rate</th>
                      <th>BMI</th>
                      <th>Fasting Glucose</th>
                      <th>Postprandial Glucose</th>
                      <th>HbA1c</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {patients.map((p, i) => (
                      <tr key={p.id}>
                        <td>{i + 1}</td>
                        <td>{p.name}</td>
                        <td className="text-center">
                          <span className={`dietician-badge ${p.assignedDietician ? 'assigned' : 'none'}`}>
                            {p.assignedDietician || "Not Assigned"}
                          </span>
                        </td>
                        <td>{p.gender}</td>
                        <td>
                          <span className={`condition-badge ${p.condition.toLowerCase()}`}>
                            {p.condition}
                          </span>
                        </td>
                        <td>{p.creatinine ?? "-"}</td>
                        <td>{p.potassium ?? "-"}</td>
                        <td>{p.sodium ?? "-"}</td>
                        <td>{p.urea ?? "-"}</td>
                        <td>{p.estimatedGFR ?? "-"}</td>
                        <td>{p.albumin ?? "-"}</td>
                        <td>{p.calcium ?? "-"}</td>
                        <td>{p.phosphate ?? "-"}</td>
                        <td>{p.uricAcid ?? "-"}</td>
                        <td>{p.cholesterolTotal ?? "-"}</td>
                        <td>{p.cholesterolLDL ?? "-"}</td>
                        <td>{p.cholesterolHDL ?? "-"}</td>
                        <td>{p.triglycerides ?? "-"}</td>
                        <td>{p.bloodPressureSystolic ?? "-"}</td>
                        <td>{p.bloodPressureDiastolic ?? "-"}</td>
                        <td>{p.heartRate ?? "-"}</td>
                        {/* <td>{p.bmi?.toFixed(1) ?? "-"}</td> */}
                        <td>{p.bmi ?? "-"}</td>
                        <td>{p.fastingGlucose ?? "-"}</td>
                        <td>{p.postprandialGlucose ?? "-"}</td>
                        <td>{p.hba1c ?? "-"}</td>

                        <td className="actions-cell">
                          <div className="action-buttons">
                            <button className="edit-btn2" onClick={() => handleEdit(p)}>Edit</button>
                            <button className="delete-btn2" onClick={() => handleDelete(p.id)}>Delete</button>
                            <button className="view-btn" onClick={() => handleViewPrescriptions(p)}>View Rx</button>
                            <button
                              className="assign-btn"
                              onClick={() => { setAssignTarget(p); setAssignName(p.assignedDietician || ""); setShowAssignModal(true); }}
                              title={p.assignedDietician ? `Assigned: ${p.assignedDietician}` : "Assign Dietician"}
                            >
                              {p.assignedDietician ? "👨‍⚕️ Reassign" : "👨‍⚕️ Assign"}
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}

                  </tbody>
                </table>
              )}
            </div>
          )}



          {activeTab === "diet" && (
            <div className="dashboard-container active diet-table-container">
              <table className="data-table diet-table-compact">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>Customer ID</th>
                    <th>Assigned Dietician</th>
                    <th>Weekly Diet</th>
                  </tr>
                </thead>

                <tbody>
                  {patients.map((p, index) => (
                    <tr key={p.id}>
                      <td className="text-center">{index + 1}</td>
                      <td className="text-left">{p.name}</td>
                      <td className="text-center">{p.customerId || "-"}</td>
                      <td className="text-center">
                        {p.dietStatus === 'pending' ? (
                          <span className="dietician-badge" style={{ backgroundColor: "#ffc107", color: "#000", fontWeight: 'bold' }}>
                            ⏳ Pending Approval
                          </span>
                        ) : (
                          <span className={`dietician-badge ${p.assignedDietician ? 'assigned' : 'none'}`}>
                            {p.assignedDietician || "Not Assigned"}
                          </span>
                        )}
                      </td>
                      <td className="text-center">
                        <button
                          className="view-btn compact-btn"
                          onClick={() => handleOpenDiet(p)}
                        >
                          View
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}


          {showDietModal && editablePlan && (
            <div className="modal-overlay">
              <div className="modal modal-large">

                <h2>
                  Weekly Diet Plan — {selectedPatient?.name} ({selectedPatient?.customerId})
                </h2>

                <div className="diet-header">
                  <span className={`diet-status ${dietPlan?.status}`}>
                    Status: {dietPlan?.status?.toUpperCase()}
                  </span>

                  {dietPlan?.status === "approved" && dietPlan?.approved_by && (
                    <span className="diet-approved-by">
                      Approved by: <strong>{dietPlan.approved_by}</strong>
                    </span>
                  )}

                  {!editMode && dietPlan?.status !== "approved" && (
                    <div className="diet-actions">
                      <button
                        className="approve-btn"
                        onClick={handleApproveDiet}
                      >
                        Approve
                      </button>

                      <button
                        className="reject-btn"
                        onClick={handleRejectDiet}
                        style={{ backgroundColor: "#dc3545", color: "white", border: "none", padding: "8px 16px", borderRadius: "6px", cursor: "pointer", fontWeight: "600" }}
                      >
                        Reject
                      </button>

                      <button
                        className="edit-btn"
                        onClick={() => setEditMode(true)}
                      >
                        Edit
                      </button>
                    </div>
                  )}
                </div>

                {/* ===== DIET TABLE START ===== */}
                {!editablePlan || !editablePlan.Monday ? (
                  <div className="diet-error">
                    <p style={{ color: "red", textAlign: "center", padding: "20px" }}>🚨 This diet plan is malformed or empty and cannot be displayed. The generation process likely failed. Please ask the patient to generate a new plan.</p>
                  </div>
                ) : (
                <table className="diet-table">
                  <thead>
                    <tr>
                      <th>Day</th>
                      {Object.keys(editablePlan.Monday).map(time => (
                        <th key={time}>{time}</th>
                      ))}
                    </tr>
                  </thead>

                  <tbody>
                    {Object.entries(editablePlan).map(([day, meals]) => (
                      <tr key={day}>
                        <td><strong>{day}</strong></td>

                        {Object.entries(meals).map(([time, meal]) => (
                          <td key={time}>
                            {editMode ? (
                              <input
                                value={meal.meal}
                                onChange={(e) =>
                                  setEditablePlan(prev => ({
                                    ...prev,
                                    [day]: {
                                      ...prev[day],
                                      [time]: {
                                        ...meal,
                                        meal: e.target.value
                                      }
                                    }
                                  }))
                                }
                              />
                            ) : (() => {
                              const trackingMeal = trackingMeals.find(
                                (m) => m.day === day && m.time === time
                              );
                              const isCompleted = trackingMeal?.status === "completed";
                              const isSkipped = trackingMeal?.status === "skipped";
                              const isAlternate = trackingMeal?.status === "alternate" || trackingMeal?.status === "alternate_upload";
                              const statusColor = isCompleted ? "#28a745" : (isSkipped ? "#dc3545" : (isAlternate ? "#17a2b8" : "inherit"));

                              return (
                                <>
                                  <div>{trackingMeal ? trackingMeal.meal_name : (meal.meal || "No meal scheduled")}</div>
                                  <small>{meal.quantity || "—"}</small><br />
                                  <small>{trackingMeal ? trackingMeal.calories : (meal.cal || 0)} cal</small>
                                  {trackingMeal && trackingMeal.status !== "pending" && (
                                    <div style={{ marginTop: '6px', fontSize: '0.9em', fontWeight: 'bold', color: statusColor }}>
                                      {isCompleted ? "✅ Completed" : (isSkipped ? "❌ Skipped" : "🔄 Alternate")}
                                    </div>
                                  )}
                                </>
                              );
                            })()}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
                )}
                {/* ===== DIET TABLE END ===== */}

                {editMode && (
                  <div className="diet-edit-actions">
                    <button className="save-btn" onClick={handleDietDraftSave}>Save</button>
                    <button
                      className="cancel-btn"
                      onClick={() => {
                        setEditablePlan(JSON.parse(dietPlan.ai_generated_plan));
                        setEditMode(false);
                      }}
                    >
                      Cancel
                    </button>
                  </div>
                )}




                <div className="diet-footer">
                  <button className="close-btn" onClick={() => setShowDietModal(false)}>
                    Close
                  </button>
                </div>
              </div>
            </div>
          )}



          {/* Reports & Settings $ Diet*/}
          {(activeTab === "reports" || activeTab === "settings") && (
            <div className="coming-soon">
              <h2>{activeTab.toUpperCase()}</h2>
              <p>This section is under development</p>
            </div>
          )}

          {/* ── Messages Tab ── */}
          {activeTab === "messages" && (
            <div className="messages-panel">
              {/* Left: conversation list */}
              <div className="conv-list">
                <div className="conv-list-header">💬 Patient Messages</div>
                {conversations.length === 0 ? (
                  <div className="conv-empty">No messages yet</div>
                ) : (
                  Object.entries(groupedConversations).map(([dietician, convs]) => (
                    <div key={dietician} className="dietician-group">
                      <div className="dietician-group-header">
                        👨‍⚕️ {dietician} ({convs.length})
                      </div>
                      {convs.map((c) => (
                        <div
                          key={c.user_id}
                          className={`conv-item ${selectedConv?.user_id === c.user_id ? "active" : ""}`}
                          onClick={() => openConversation(c)}
                        >
                          <div className="conv-avatar">{(c.full_name || "?")[0].toUpperCase()}</div>
                          <div className="conv-info">
                            <div className="conv-name">{c.full_name}</div>
                            <div className="conv-last">
                              {c.last_message?.slice(0, 30)}
                              {c.last_message?.length > 30 ? "..." : ""}
                            </div>
                          </div>
                          {c.unread_count > 0 && (
                            <span className="conv-badge">{c.unread_count}</span>
                          )}
                        </div>
                      ))}
                    </div>
                  ))
                )}
              </div>

              {/* Right: chat thread */}
              <div className="conv-thread">
                {!selectedConv ? (
                  <div className="conv-empty-thread">
                    <div style={{ fontSize: 48 }}>💬</div>
                    <p>Select a conversation to view messages</p>
                  </div>
                ) : (
                  <>
                    <div className="conv-thread-header">
                      <strong>{selectedConv.full_name}</strong>
                      {selectedConv.assigned_dietician && (
                        <span className="conv-assigned">Dietician: {selectedConv.assigned_dietician}</span>
                      )}
                    </div>
                    <div className="conv-messages">
                      {convLoading ? (
                        <div className="conv-loading">Loading messages...</div>
                      ) : (
                        convMessages.map((m) => (
                          <div key={m.id} className={`conv-bubble ${m.sender}`}>
                            <div className="conv-bubble-text">{m.message}</div>
                            <div className="conv-bubble-time">
                              {m.sender === "dietician" ? `👨‍⚕️ ${m.dietician || "Admin"} · ` : "Patient · "}
                              {new Date(m.timestamp).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true })}
                            </div>
                          </div>
                        ))
                      )}
                      {patientTyping && (
                        <div className="conv-bubble patient">
                          <div className="conv-bubble-text typing-dots">
                            <span/><span/><span/>
                          </div>
                        </div>
                      )}
                      <div ref={adminMsgEndRef} />
                    </div>
                    <div className="conv-input-area">
                      <input
                        type="text"
                        value={adminInput}
                        onChange={(e) => setAdminInput(e.target.value)}
                        onKeyDown={(e) => e.key === "Enter" && sendAdminReply()}
                        placeholder={`Reply to ${selectedConv.full_name}...`}
                        className="conv-input"
                      />
                      <button onClick={sendAdminReply} className="conv-send-btn" disabled={!adminInput.trim()}>
                        Send ➤
                      </button>
                    </div>
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      </main>

      {/* ================= EDIT MEDICAL MODAL ================= */}
      {showEditModal && (
        <div className="modal-overlay">
          <div className="modal modal-large">
            <h2>Edit Medical Data</h2>

            <div className="modal-grid">

              {/* <input type="number" placeholder="Creatinine"
          value={formData.creatinine || ""}
          onChange={(e) => setFormData({ ...formData, creatinine: e.target.value })}
        /> */}
              <div className="form-group">
                <label>Creatinine</label>
                <input type="number" placeholder="Creatinine"
                  value={formData.creatinine || ""}
                  onChange={(e) => setFormData({ ...formData, creatinine: e.target.value })}
                />
              </div>

              <div className="form-group">
                <label>Potassium</label>
                <input type="number" placeholder="Potassium"
                  value={formData.potassium || ""}
                  onChange={(e) => setFormData({ ...formData, potassium: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Sodium</label>
                <input type="number" placeholder="Sodium"
                  value={formData.sodium || ""}
                  onChange={(e) => setFormData({ ...formData, sodium: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Urea</label>
                <input type="number" placeholder="Urea"
                  value={formData.urea || ""}
                  onChange={(e) => setFormData({ ...formData, urea: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Estimated GFR</label>
                <input type="number" placeholder="Estimated GFR"
                  value={formData.estimatedGFR || ""}
                  onChange={(e) => setFormData({ ...formData, estimatedGFR: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Albumin</label>
                <input type="number" placeholder="Albumin"
                  value={formData.albumin || ""}
                  onChange={(e) => setFormData({ ...formData, albumin: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Calcium</label>
                <input type="number" placeholder="Calcium"
                  value={formData.calcium || ""}
                  onChange={(e) => setFormData({ ...formData, calcium: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Phosphate</label>
                <input type="number" placeholder="Phosphate"
                  value={formData.phosphate || ""}
                  onChange={(e) => setFormData({ ...formData, phosphate: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Uric Acid</label>
                <input type="number" placeholder="Uric Acid"
                  value={formData.uricAcid || ""}
                  onChange={(e) => setFormData({ ...formData, uricAcid: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Cholesterol Total</label>
                <input type="number" placeholder="Cholesterol Total"
                  value={formData.cholesterolTotal || ""}
                  onChange={(e) => setFormData({ ...formData, cholesterolTotal: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Cholesterol LDL</label>
                <input type="number" placeholder="Cholesterol LDL"
                  value={formData.cholesterolLDL || ""}
                  onChange={(e) => setFormData({ ...formData, cholesterolLDL: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Cholesterol HDL</label>
                <input type="number" placeholder="Cholesterol HDL"
                  value={formData.cholesterolHDL || ""}
                  onChange={(e) => setFormData({ ...formData, cholesterolHDL: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Triglycerides</label>
                <input type="number" placeholder="Triglycerides"
                  value={formData.triglycerides || ""}
                  onChange={(e) => setFormData({ ...formData, triglycerides: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>BP Systolic</label>
                <input type="number" placeholder="BP Systolic"
                  value={formData.bloodPressureSystolic || ""}
                  onChange={(e) => setFormData({ ...formData, bloodPressureSystolic: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>BP Diastolic</label>
                <input type="number" placeholder="BP Diastolic"
                  value={formData.bloodPressureDiastolic || ""}
                  onChange={(e) => setFormData({ ...formData, bloodPressureDiastolic: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Heart Rate</label>
                <input type="number" placeholder="Heart Rate"
                  value={formData.heartRate || ""}
                  onChange={(e) => setFormData({ ...formData, heartRate: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>BMI</label>
                <input type="number" placeholder="BMI"
                  value={formData.bmi || ""}
                  onChange={(e) => setFormData({ ...formData, bmi: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>Fasting Glucose</label>
                <input type="number" placeholder="Fasting Glucose"
                  value={formData.fastingGlucose || ""}
                  onChange={(e) => setFormData({ ...formData, fastingGlucose: e.target.value })}
                />
              </div>

              <div className="form-group">
                <label>Postprandial Glucose</label>
                <input type="number" placeholder="Postprandial Glucose"
                  value={formData.postprandialGlucose || ""}
                  onChange={(e) => setFormData({ ...formData, postprandialGlucose: e.target.value })}
                />
              </div>


              <div className="form-group">
                <label>HbA1c</label>
                <input type="number" placeholder="HbA1c"
                  value={formData.hba1c || ""}
                  onChange={(e) => setFormData({ ...formData, hba1c: e.target.value })}
                />

              </div>
            </div>

            <div className="modal-actions">
              <button className="edit-btn" onClick={handleSaveMedical}>
                Save
              </button>
              <button className="close-btn" onClick={() => setShowEditModal(false)}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}


      {/* ================= PRESCRIPTION MODAL ================= */}
      {showPrescriptionModal && (
        <div className="modal-overlay">
          <div className="modal modal-large">
            <h2>
              Prescriptions – {selectedPatient?.name}
            </h2>

            {loadingPrescriptions ? (
              <p>Loading prescriptions...</p>
            ) : prescriptions.length === 0 ? (
              <p>No prescriptions uploaded.</p>
            ) : (
              <div className="prescription-grid">
                {prescriptions.map((file) => (

                  <div
                    key={file.id}
                    className="prescription-card"
                    onClick={() => openPrescriptionViewer(file)}
                    style={{ cursor: "pointer" }}
                  >
                    <p>{file.file_name}</p>


                    {file.file_type.startsWith("image") ? (
                      <img
                        src={`/api${file.file_path}`}
                        alt={file.file_name}
                        className="prescription-image"
                      />
                    ) : (
                      <a
                        href={`/api${file.file_path}`}
                        target="_blank"
                        rel="noreferrer"
                      >
                        View PDF
                      </a>
                    )}
                  </div>
                ))}
              </div>
            )}

            <button className="close-btn" onClick={() => setShowPrescriptionModal(false)}>
              Close
            </button>
          </div>
        </div>
      )}


      {viewingPrescription &&
        viewingPrescription.type.startsWith("image/") && (
          <div
            className="prescription-viewer-overlay"
            onClick={() => setViewingPrescription(null)}
          >
            <div
              className="prescription-viewer-content"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="viewer-header">
                <h3>{viewingPrescription.name}</h3>
                <button
                  className="close-viewer-btn"
                  onClick={() => setViewingPrescription(null)}
                >
                  ×
                </button>
              </div>

              <div className="viewer-body">
                <img
                  src={viewingPrescription.url}
                  alt={viewingPrescription.name}
                  className="prescription-image"
                />
              </div>
            </div>
          </div>
        )}


      {popup.show && (
        <div className="popup-overlay">
          <div className={`popup-modal ${popup.type}`}>
            <p>{popup.message}</p>
            <button onClick={() => setPopup({ ...popup, show: false })}>
              OK
            </button>
          </div>
        </div>
      )}

      {/* Assign Dietician Modal */}
      {showAssignModal && assignTarget && (
        <div className="modal-overlay">
          <div className="modal" style={{ maxWidth: 420 }}>
            <h2>👨‍⚕️ Assign Dietician</h2>
            <p style={{ color: "#64748b", marginBottom: 16 }}>Patient: <strong>{assignTarget.name}</strong></p>
            <div className="form-group">
              <label>Dietician Name</label>
              <input
                type="text"
                value={assignName}
                onChange={(e) => setAssignName(e.target.value)}
                placeholder="e.g. Dr. Priya Sharma"
                onKeyDown={(e) => e.key === "Enter" && handleAssignDietician()}
              />
            </div>
            <div className="modal-actions">
              <button className="approve-btn" onClick={handleAssignDietician} disabled={assignLoading}>
                {assignLoading ? "Saving..." : "Assign"}
              </button>
              <button className="close-btn" onClick={() => { setShowAssignModal(false); setAssignName(""); setAssignTarget(null); }}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}


    </div>
  );
}